-- ==============================================================================
-- KESEHATAN FEEDLOT — SUPABASE SCHEMA
-- Mirrors the IndexedDB structure of the local PWA
-- ==============================================================================

-- 1. USERS
-- Stores local authentication data. Note: Passwords are plain text as per app design.
create table public.users (
  username text primary key,
  password text not null,
  role text default 'user',
  permissions jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 2. MASTER DATA
-- Key-value pairs for dropdowns. Composite Primary Key matches IndexedDB keyPath ['type', 'value'].
create table public.master_data (
  type text not null,
  value text not null,
  created_at timestamptz default now(),
  primary key (type, value)
);

-- 3. SETTINGS
-- App configurations.
create table public.settings (
  key text primary key,
  value text, -- JSON string or plain text
  updated_at timestamptz default now()
);

-- 4. TREATMENT
-- Main cattle treatment records.
create table public.treatment (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  shipment text,
  eartag text,
  penanggung_jawab text, -- mapped from JS CamelCase 'penanggungJawab' if needed, or stick to JS naming
  berat numeric,
  jenis_pakan text,
  treat_ke integer,
  diagnosa text,
  pen_asal text,
  pen_akhir text,
  obat jsonb, -- Array of objects: [{ name, dosis, ... }]
  foto text, -- Base64 string
  synced boolean default false,
  created_at timestamptz default now()
);
-- Create indexes for performance
create index idx_treatment_tanggal on public.treatment(tanggal);
create index idx_treatment_eartag on public.treatment(eartag);
create index idx_treatment_shipment on public.treatment(shipment);

-- 5. MOVING
-- Cattle movement records.
create table public.moving (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  shipment text,
  eartag text,
  penanggung_jawab text,
  keterangan text,
  pen_awal text,
  pen_akhir text,
  salvage boolean default false,
  foto text, -- Base64
  synced boolean default false,
  created_at timestamptz default now()
);
create index idx_moving_tanggal on public.moving(tanggal);
create index idx_moving_eartag on public.moving(eartag);

-- 6. PENGAMBILAN OBAT
-- Medicine pickup log.
create table public.pengambilan_obat (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  penanggung_jawab text,
  lines jsonb, -- Array of items: [{ name, qty }]
  synced boolean default false,
  created_at timestamptz default now()
);
create index idx_pobj_tanggal on public.pengambilan_obat(tanggal);

-- 7. PENAMBAHAN OBAT
-- Medicine stock entry log.
create table public.penambahan_obat (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  penanggung_jawab text,
  lines jsonb, -- Array: [{ date, name, qty }]
  synced boolean default false,
  created_at timestamptz default now()
);
create index idx_pamb_tanggal on public.penambahan_obat(tanggal);

-- 8. PEN TRIAL
-- Pen trial / experiment groups.
create table public.pen_trial (
  id bigint generated by default as identity primary key,
  tanggal date not null,
  penanggung_jawab text,
  kandang text,
  pen text, -- Array or string? DB stores text usually unless multiple pens per trial
  synced boolean default false,
  created_at timestamptz default now()
);
create index idx_pentrial_date on public.pen_trial(tanggal);

-- 9. SALVAGE
-- Forced sale records.
create table public.salvage (
  id bigint generated by default as identity primary key,
  tanggal date,
  eartag text,
  keterangan text,
  foto text,
  synced boolean default false,
  created_at timestamptz default now()
);

-- 10. SYNC LOG
-- History of sync actions.
create table public.sync_log (
  id bigint generated by default as identity primary key,
  timestamp timestamptz default now(),
  action text,
  detail text
);


-- ==============================================================================
-- ROW LEVEL SECURITY (RLS)
-- Use this if you want to allow anonymous access (since app uses local auth + anon key).
-- WARNING: This makes the database publicly readable/writable with the anon key.
-- ==============================================================================

alter table public.users enable row level security;
alter table public.master_data enable row level security;
alter table public.settings enable row level security;
alter table public.treatment enable row level security;
alter table public.moving enable row level security;
alter table public.pengambilan_obat enable row level security;
alter table public.penambahan_obat enable row level security;
alter table public.pen_trial enable row level security;
alter table public.salvage enable row level security;
alter table public.sync_log enable row level security;

-- Policy to allow all operations for anon (public) role
create policy "Enable access for all users" on public.users for all using (true) with check (true);
create policy "Enable access for all users" on public.master_data for all using (true) with check (true);
create policy "Enable access for all users" on public.settings for all using (true) with check (true);
create policy "Enable access for all users" on public.treatment for all using (true) with check (true);
create policy "Enable access for all users" on public.moving for all using (true) with check (true);
create policy "Enable access for all users" on public.pengambilan_obat for all using (true) with check (true);
create policy "Enable access for all users" on public.penambahan_obat for all using (true) with check (true);
create policy "Enable access for all users" on public.pen_trial for all using (true) with check (true);
create policy "Enable access for all users" on public.salvage for all using (true) with check (true);
create policy "Enable access for all users" on public.sync_log for all using (true) with check (true);
